
package com.haulmont.thesis.crm.core.app.bp.efwebservice1c;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.datatype.XMLGregorianCalendar;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

import com.haulmont.thesis.crm.core.app.bp.efdata.*;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "EfWebService1CPortType", targetNamespace = "http://EfWebService1C")
@XmlSeeAlso({
        com.haulmont.thesis.crm.core.app.bp.efdata.ObjectFactory.class,
        com.haulmont.thesis.crm.core.app.bp.efwebservice1c.ObjectFactory.class
})
public interface EfWebService1CPortType {


    /**
     * 
     * @param params
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "http://EfWebService1C#EfWebService1C:setContract")
    @WebResult(targetNamespace = "http://EfWebService1C")
    @RequestWrapper(localName = "setContract", targetNamespace = "http://EfWebService1C", className = "efwebservice1c.SetContract")
    @ResponseWrapper(localName = "setContractResponse", targetNamespace = "http://EfWebService1C", className = "efwebservice1c.SetContractResponse")
    public String setContract(
        @WebParam(name = "Params", targetNamespace = "http://EfWebService1C")
        Pact params);

    /**
     * 
     * @param params
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "http://EfWebService1C#EfWebService1C:setProject")
    @WebResult(targetNamespace = "http://EfWebService1C")
    @RequestWrapper(localName = "setProject", targetNamespace = "http://EfWebService1C", className = "efwebservice1c.SetProject")
    @ResponseWrapper(localName = "setProjectResponse", targetNamespace = "http://EfWebService1C", className = "efwebservice1c.SetProjectResponse")
    public String setProject(
        @WebParam(name = "Params", targetNamespace = "http://EfWebService1C")
        Project params);

    /**
     * 
     * @param params
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "http://EfWebService1C#EfWebService1C:setAccount")
    @WebResult(targetNamespace = "http://EfWebService1C")
    @RequestWrapper(localName = "setAccount", targetNamespace = "http://EfWebService1C", className = "efwebservice1c.SetAccount")
    @ResponseWrapper(localName = "setAccountResponse", targetNamespace = "http://EfWebService1C", className = "efwebservice1c.SetAccountResponse")
    public String setAccount(
        @WebParam(name = "Params", targetNamespace = "http://EfWebService1C")
        Account params);

    /**
     * 
     * @param params
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "http://EfWebService1C#EfWebService1C:setNomenclature")
    @WebResult(targetNamespace = "http://EfWebService1C")
    @RequestWrapper(localName = "setNomenclature", targetNamespace = "http://EfWebService1C", className = "efwebservice1c.SetNomenclature")
    @ResponseWrapper(localName = "setNomenclatureResponse", targetNamespace = "http://EfWebService1C", className = "efwebservice1c.SetNomenclatureResponse")
    public String setNomenclature(
        @WebParam(name = "Params", targetNamespace = "http://EfWebService1C")
        Item params);

    /**
     * 
     * @param params
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "http://EfWebService1C#EfWebService1C:setOrd")
    @WebResult(targetNamespace = "http://EfWebService1C")
    @RequestWrapper(localName = "setOrd", targetNamespace = "http://EfWebService1C", className = "efwebservice1c.SetOrd")
    @ResponseWrapper(localName = "setOrdResponse", targetNamespace = "http://EfWebService1C", className = "efwebservice1c.SetOrdResponse")
    public String setOrd(
        @WebParam(name = "Params", targetNamespace = "http://EfWebService1C")
        Doc params);

    /**
     * 
     * @param params
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "http://EfWebService1C#EfWebService1C:setInv")
    @WebResult(targetNamespace = "http://EfWebService1C")
    @RequestWrapper(localName = "setInv", targetNamespace = "http://EfWebService1C", className = "efwebservice1c.SetInv")
    @ResponseWrapper(localName = "setInvResponse", targetNamespace = "http://EfWebService1C", className = "efwebservice1c.SetInvResponse")
    public String setInv(
        @WebParam(name = "Params", targetNamespace = "http://EfWebService1C")
        Doc params);

    /**
     * 
     * @param params
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "http://EfWebService1C#EfWebService1C:setAc")
    @WebResult(targetNamespace = "http://EfWebService1C")
    @RequestWrapper(localName = "setAc", targetNamespace = "http://EfWebService1C", className = "efwebservice1c.SetAc")
    @ResponseWrapper(localName = "setAcResponse", targetNamespace = "http://EfWebService1C", className = "efwebservice1c.SetAcResponse")
    public String setAc(
        @WebParam(name = "Params", targetNamespace = "http://EfWebService1C")
        Doc params);

    /**
     * 
     * @return
     *     returns efdata.PayList
     */
    @WebMethod(action = "http://EfWebService1C#EfWebService1C:getPayList")
    @WebResult(targetNamespace = "http://EfWebService1C")
    @RequestWrapper(localName = "getPayList", targetNamespace = "http://EfWebService1C", className = "efwebservice1c.GetPayList")
    @ResponseWrapper(localName = "getPayListResponse", targetNamespace = "http://EfWebService1C", className = "efwebservice1c.GetPayListResponse")
    public PayList getPayList();

    /**
     * 
     * @param params
     * @return
     *     returns efdata.ReferenceList
     */
    @WebMethod(action = "http://EfWebService1C#EfWebService1C:getReferenceList")
    @WebResult(targetNamespace = "http://EfWebService1C")
    @RequestWrapper(localName = "getReferenceList", targetNamespace = "http://EfWebService1C", className = "efwebservice1c.GetReferenceList")
    @ResponseWrapper(localName = "getReferenceListResponse", targetNamespace = "http://EfWebService1C", className = "efwebservice1c.GetReferenceListResponse")
    public ReferenceList getReferenceList(
        @WebParam(name = "Params", targetNamespace = "http://EfWebService1C")
        ParamsGeneric params);

    /**
     * 
     * @param params
     * @return
     *     returns efdata.DocList
     */
    @WebMethod(action = "http://EfWebService1C#EfWebService1C:getDocList")
    @WebResult(targetNamespace = "http://EfWebService1C")
    @RequestWrapper(localName = "getDocList", targetNamespace = "http://EfWebService1C", className = "efwebservice1c.GetDocList")
    @ResponseWrapper(localName = "getDocListResponse", targetNamespace = "http://EfWebService1C", className = "efwebservice1c.GetDocListResponse")
    public DocList getDocList(
        @WebParam(name = "Params", targetNamespace = "http://EfWebService1C")
        ParamsGeneric params);

    /**
     *
     * @param params
     * @return
     *     returns efdata.Vat
     */
    @WebMethod(action = "http://EfWebService1C#EfWebService1C:setVat")
    @WebResult(targetNamespace = "http://EfWebService1C")
    @RequestWrapper(localName = "setVat", targetNamespace = "http://EfWebService1C", className = "efwebservice1c.SetVat")
    @ResponseWrapper(localName = "setVatResponse", targetNamespace = "http://EfWebService1C", className = "efwebservice1c.SetVatResponse")
    public Vat setVat(
            @WebParam(name = "Params", targetNamespace = "http://EfWebService1C")
                    Vat params);

    /**
     *
     * @param params
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "http://EfWebService1C#EfWebService1C:setCash")
    @WebResult(targetNamespace = "http://EfWebService1C")
    @RequestWrapper(localName = "setCash", targetNamespace = "http://EfWebService1C", className = "efwebservice1c.SetCash")
    @ResponseWrapper(localName = "setCashResponse", targetNamespace = "http://EfWebService1C", className = "efwebservice1c.SetCashResponse")
    public String setCash(
            @WebParam(name = "Params", targetNamespace = "http://EfWebService1C")
                    Cash params);

    /**
     *
     * @return
     *     returns javax.xml.datatype.XMLGregorianCalendar
     */
    @WebMethod(action = "http://EfWebService1C#EfWebService1C:getDisableDate")
    @WebResult(targetNamespace = "http://EfWebService1C")
    @RequestWrapper(localName = "getDisableDate", targetNamespace = "http://EfWebService1C", className = "efwebservice1c.GetDisableDate")
    @ResponseWrapper(localName = "getDisableDateResponse", targetNamespace = "http://EfWebService1C", className = "efwebservice1c.GetDisableDateResponse")
    public XMLGregorianCalendar getDisableDate();

    /**
     *
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "http://EfWebService1C#EfWebService1C:refreshNumberObject")
    @WebResult(targetNamespace = "http://EfWebService1C")
    @RequestWrapper(localName = "refreshNumberObject", targetNamespace = "http://EfWebService1C", className = "efwebservice1c.RefreshNumberObject")
    @ResponseWrapper(localName = "refreshNumberObjectResponse", targetNamespace = "http://EfWebService1C", className = "efwebservice1c.RefreshNumberObjectResponse")
    public String refreshNumberObject();

    /**
     *
     * @param params
     * @return
     *     returns efdata.PayOrd
     */
    @WebMethod(action = "http://EfWebService1C#EfWebService1C:setPayOrd")
    @WebResult(targetNamespace = "http://EfWebService1C")
    @RequestWrapper(localName = "setPayOrd", targetNamespace = "http://EfWebService1C", className = "efwebservice1c.SetPayOrd")
    @ResponseWrapper(localName = "setPayOrdResponse", targetNamespace = "http://EfWebService1C", className = "efwebservice1c.SetPayOrdResponse")
    public PayOrd setPayOrd(
            @WebParam(name = "Params", targetNamespace = "http://EfWebService1C")
                    PayOrd params);

    /**
     *
     * @param params
     * @return
     *     returns efdata.ListParamStatus
     */
    @WebMethod(action = "http://EfWebService1C#EfWebService1C:getStatusList")
    @WebResult(targetNamespace = "http://EfWebService1C")
    @RequestWrapper(localName = "getStatusList", targetNamespace = "http://EfWebService1C", className = "efwebservice1c.GetStatusList")
    @ResponseWrapper(localName = "getStatusListResponse", targetNamespace = "http://EfWebService1C", className = "efwebservice1c.GetStatusListResponse")
    public ListParamStatus getStatusList(
            @WebParam(name = "Params", targetNamespace = "http://EfWebService1C")
                    ListParamStatus params);

}
